# Generated by Django 6.0.2 on 2026-02-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='library',
            name='open_time',
        ),
        migrations.AddField(
            model_name='library',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
