# Generated by Django 6.0.2 on 2026-02-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_remove_library_close_time_remove_library_open_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='distance',
        ),
        migrations.AddField(
            model_name='library',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='library',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
