# Generated by Django 6.0.2 on 2026-03-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_remove_library_distance_library_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Upload a UPI QR code for users to scan when paying fines.', null=True, upload_to='library_qrs/'),
        ),
    ]
