# Generated by Django 6.0.2 on 2026-03-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_library_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='logo',
            field=models.ImageField(blank=True, help_text="Upload the library's logo image.", null=True, upload_to='library_logos/'),
        ),
    ]
