# Generated by Django 6.0.2 on 2026-02-27 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('NOVEL', 'Novel'), ('PROGRAMMING', 'Programming'), ('HISTORY', 'History'), ('SCIENCE', 'Science')], default='NOVEL', max_length=50)),
                ('total_copies', models.IntegerField(default=1)),
                ('available_copies', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images/')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='libraries.library')),
            ],
        ),
    ]
