# Generated by Django 6.0.2 on 2026-02-28 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_description_book_fine_per_day_book_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'book')},
        ),
    ]
