# Generated by Django 6.0.2 on 2026-03-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_review_rating_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('PROGRAMMING', 'Programming'), ('FICTION', 'Fiction'), ('SELFHELP', 'Self Help'), ('HISTORY', 'History'), ('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('UPSC', 'UPSC'), ('MANGA', 'Anime / Manga'), ('LEARNING', 'Common Learning Books')], max_length=50),
        ),
    ]
