# Generated by Django 6.0.2 on 2026-03-26 11:37

import django.db.models.deletion
from django.db import migrations, models


def migrate_categories(apps, schema_editor):
    Book = apps.get_model('catalog', 'Book')
    Category = apps.get_model('catalog', 'Category')

    for book in Book.objects.all():
        category_name = book.category
        if category_name:
            cat, _ = Category.objects.get_or_create(name=category_name)
            book.category = str(cat.id)
            book.save()

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RunPython(migrate_categories),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.category'),
        ),
    ]
